# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Example

on:
  pull_request:
    branches: [ master ]
    types:
      - closed
jobs:
  publish-npm:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install ğŸ”§
        run: npm i --legacy-peer-deps

      - name: Build Lib ğŸ—ï¸
        run: npm run build:lib

      - name: Init Example
        run: npm run init-example

      - name: Build example
        run: npm run build:example

      - name: Deploy to GH Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build

      - name: Publish Npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.KNE_PACKAGE_PUBLISH}}
        run: cd example && npm publish --access=public
      ## è¯·ä¿®æ”¹å¯¹åº”çš„packageNameåå–æ¶ˆä»¥ä¸‹å‘½ä»¤çš„æ³¨é‡Š
      - name: Sync To Cnpm
        run: npm i -g cnpm && cnpm sync @kne-example/react-form
